baseURL: https://property.opensourcelaw.ca/
title: "Land & Lawscapes: An Open Casebook"

# Hugo Book theme as a Hugo module

module:
  imports:
  - path: github.com/radish-es/casebook-layouts
  # - path: github.com/radish-es/casebook-property-modules
  #   mounts:
  #   - source: content/cases
  #     target: content/cases
  - path: github.com/alex-shpak/hugo-book

# Book configuration
#disablePathToLower: true

enableGitInfo: true

params:
  BookTheme: "light"
  BookToC: true
  BookSection: "*"
  BookDateFormat: "January 2, 2006"
  # BookLogo: /logo.png
  # BookMenuBundle: /menu

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  doctrine: doctrines